/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Test;

import java.util.Stack;

public class Library {
    public static void main(String ...args) {
        // someLibraryMethod("{{}({}89472");
        // System.out.println('j' + 'a' + 'v' + 'a');
        System.out.println(isPowerOf(10, 1000));
        System.out.println(Math.log(10)*Math.log(3));
    }

    public static boolean isPowerOf(Integer p,Integer n){
        // int val1 = (int)(Math.log(n)/Math.log(n));
        double val2 = Math.log(n)/Math.log(p);
        int val1 = (int)Math.log(n)/(int)Math.log(p);
        return Math.abs(val1-val2) < 1e-4;
    }
    public static void someLibraryMethod(String st) {
        Stack<Character> stack = new Stack<>();
        int counter =0;
        for (int i=0; i< st.length();i++) {
            if(st.charAt(i)=='{'){
                stack.push(st.charAt(i));
            } else if(st.charAt(i)=='}'){
                stack.pop();
                counter++;
            }
        }
        if(stack.isEmpty()){
            System.out.println(counter);
        } else{
            System.out.println("invalid");
        }
    }
}
